feat:
  - head-branch: ["^feature", "feature", "feat"]

fix:
  - head-branch: ["^fix", "fixed"]

test:
  - head-branch: ["^test", "test", "tests"]

docs:
  - head-branch: ["^documentation", "documentation", "^docs", "docs"]
  - changed-files:
      - any-glob-to-any-file:
          - "**/docs/**"

db:
  - changed-files:
      - any-glob-to-any-file:
          - packages/db/**

components:
  - changed-files:
      - any-glob-to-any-file:
          - packages/components/**

constants:
  - changed-files:
      - any-glob-to-any-file:
          - packages/constants/**

core:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/**

security:
  - changed-files:
      - any-glob-to-any-file:
          - packages/security/**
api:
  - changed-files:
      - any-glob-to-any-file:
          - apps/api/**

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - tooling/**

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

monitor:
  - changed-files:
      - any-glob-to-any-file:
          - packages/monitor/**

infra:
  - changed-files:
      - any-glob-to-any-file:
          - infrastructure/**

env:
  - changed-files:
      - any-glob-to-any-file:
          - packages/env/*
blog:
  - changed-files:
      - any-glob-to-any-file:
          - apps/blog/*

www:
  - changed-files:
      - any-glob-to-any-file:
          - apps/www/*

design:
  - changed-files:
      - any-glob-to-any-file:
          - packages/design/*

seo:
  - changed-files:
      - any-glob-to-any-file:
          - packages/seo/*

analytics:
  - changed-files:
      - any-glob-to-any-file:
          - packages/analytics/*

logger:
  - changed-files:
      - any-glob-to-any-file:
          - packages/logger/*

email:
  - changed-files:
      - any-glob-to-any-file:
          - packages/email/*

storage:
  - changed-files:
      - any-glob-to-any-file:
          - packages/storage/*

rate-limiter:
  - changed-files:
      - any-glob-to-any-file:
          - packages/rate-limiter/*

scheduler:
  - changed-files:
      - any-glob-to-any-file:
          - packages/scheduler/**
