name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      app:
        description: "Which app to deploy?"
        required: true
        default: "both"
        type: choice
        options:
          - www
          - continuum
          - both
      environment:
        description: "Target environment"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - production

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secrets-leaks:
    uses: ./.github/workflows/on-workflow-call-secrets-leaks.yml
    secrets: inherit

  validate-env:
    needs: [secrets-leaks]
    uses: ./.github/workflows/on-workflow-call-validate-env.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/on-workflow-call-format.yml
    secrets: inherit

  dependencies-check:
    uses: ./.github/workflows/on-workflow-call-dependencies-check.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/on-workflow-call-lint.yml
    secrets: inherit

  build:
    needs: [validate-env]
    uses: ./.github/workflows/on-workflow-call-build.yml
    secrets: inherit

  test:
    needs: [validate-env]
    uses: ./.github/workflows/on-workflow-call-test.yml
    secrets: inherit

  db-migrate-ephermal:
    needs: [validate-env]
    uses: ./.github/workflows/on-workflow-call-db-migrate-ephermal.yml
    secrets: inherit

  mergeable:
    needs:
      - validate-env
      - format
      - lint
      - test
      - secrets-leaks
      - build
      - dependencies-check
      - db-migrate-ephermal
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  #### PREVIEW
  # requires manual trigger by the owner
  preview-deployment:
    needs: [mergeable]
    if: (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'preview')
    uses: ./.github/workflows/on-workflow-call-trigger-deployment.yml
    with:
      environment: preview
    secrets: inherit

  www-preview-deployment:
    needs: [preview-deployment]
    if: needs.preview-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'www' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-serverless-deployment.yml
    with:
      environment: preview
      app: www
    secrets: inherit

  continuum-preview-deployment:
    needs: [preview-deployment]
    if: needs.preview-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'continuum' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      environment: preview
      app: continuum
    secrets: inherit

  api-preview-deployment:
    needs: [preview-deployment]
    if: needs.preview-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'continuum' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      environment: preview
      app: api
    secrets: inherit

  ##### PRODUCTION
  # requires manual trigger by the owner
  production-deployment:
    needs: [mergeable]
    if: (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'production')
    uses: ./.github/workflows/on-workflow-call-trigger-deployment.yml
    with:
      environment: production
    secrets: inherit

  www-production-deployment:
    needs: [production-deployment]
    if: needs.production-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'www' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-serverless-deployment.yml
    with:
      environment: production
      app: www
    secrets: inherit

  continuum-production-deployment:
    needs: [production-deployment]
    if: needs.production-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'continuum' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      environment: production
      app: continuum
    secrets: inherit

  api-production-deployment:
    needs: [production-deployment]
    if: needs.production-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'continuum' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      environment: production
      app: api
    secrets: inherit
