name: Cron / Purge View Window

on:
  schedule:
    # run every 2 days at 03:07 UTC
    - cron: "7 3 */2 * *"
  workflow_dispatch:

jobs:
  purge_view_window:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULE_SYNC_PAT }}

      - name: Purge View Window
        shell: bash
        run: .github/scripts/cron/purge-view-window

      - name: Notify • cron ok
        if: success()
        uses: rccyx/notify@main
        with:
          token: ${{ secrets.X_API_TOKEN }}

          title: "Cron Succeeded"
          message: >-
            ## Details

            - Monthly trash purge succeeded on ${{ env.NEXT_PUBLIC_API_URL }}.

            - **Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Notify • cron fail
        if: failure()
        uses: rccyx/notify@main
        with:
          token: ${{ secrets.INTERNAL_NOTIFICATION_TOKEN }}

          title: "Cron Failed"
          message: >-
            ## Details

            - Monthly trash purge failed on ${{ env.NEXT_PUBLIC_API_URL }}.

            - **Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
