name: CD / Serverless Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment to deploy to (preview or production)"
      app:
        required: true
        type: string
        description: "App name, follows the folder structure of ../../packages"

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULE_SYNC_PAT }}

      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/db-migrate
        with:
          comment_on_pr: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}

        # hardcored part
      - name: Select Vercel Project Secrets
        id: vercel-secrets
        run: |
          if [ "${{ inputs.app }}" = "continuum" ]; then
            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_CONTINUUM_PROJECT_ID }}" >> $GITHUB_OUTPUT
          else
            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_WWW_PROJECT_ID }}" >> $GITHUB_OUTPUT
          fi

          # Common ones
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_OUTPUT
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_OUTPUT

        # normal
      - uses: ./.github/actions/vercel-deploy
        with:
          environment: ${{ inputs.environment }}
          app: ${{ inputs.app }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          VERCEL_TOKEN: ${{ steps.vercel-secrets.outputs.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ steps.vercel-secrets.outputs.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ steps.vercel-secrets.outputs.VERCEL_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
