name: CD / Docker App Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app:
        required: true
        type: string
        description: basically the app under ../../packages

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULE_SYNC_PAT }}

      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/db-migrate
        with:
          comment_on_pr: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}

      - uses: ./.github/actions/container-deploy
        with:
          environment: ${{ inputs.environment }}
          app: ${{ inputs.app }}
          CONTAINER_SERVICE_TOKEN: ${{ secrets.CONTAINER_SERVICE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
