name: PR / summarizer

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULE_SYNC_PAT }}

      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - name: Summarize PR
        uses: rccyx/pr-summarizer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ env.OPENAI_PR_SUMMARIZER_TOKEN }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: "*.lock,dist/**,*.min.js,*.map"
          max_files: "130"
          owner: "author"
          override_summary: "true"
