name: CI / Database Fresh Migration On Ephermal DB

on:
  workflow_call:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULE_SYNC_PAT }}

      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/setup-ephermal-db
      - name: Run fresh migrations on the ephermal database
        shell: bash
        run: |
          # I'm already using zod for validation against which DB is which, but extra paranoia won't hurt
          if [[ "$DATABASE_URL" != *"localhost"* ]] && [[ "$DATABASE_URL" != *"127.0.0.1"* ]]; then
            echo "❌ DATABASE_URL is not local! Aborting."
            exit 1
          fi

          echo "Running migration reset..."
          pnpm --filter @rccyx/db migrate:reset --force

          echo "Validating migrations..."
          pnpm --filter @rccyx/db migrate:status

          # deploying migrations
          pnpm --filter @rccyx/db migrate:deploy

      - name: stop ephermal DB
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          echo "Cleaning up..."
          pnpm --filter @rccyx/db stop
