name: CI / DB Migrate

description: Run database migrations (against the real DB)

inputs:
  comment_on_pr:
    required: true
    description: "Whether to comment on the PR ('yes' or 'no') after running the migration"

runs:
  using: "composite"
  steps:
    - name: Mask database url if not done already
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${DATABASE_URL:-}" ]]; then
          echo "DATABASE_URL is not set"; exit 1
        fi
        if [[ -z "${DIRECT_URL:-}" ]]; then
          echo "DIRECT_URL is not set"; exit 1
        fi
        echo "::add-mask::$DATABASE_URL"
        echo "::add-mask::$DIRECT_URL"

    - name: Deploy pending migrations on the $NEXT_PUBLIC_CURRENT_ENV database
      shell: bash
      run: |
        pnpm --filter @rccyx/db migrate:deploy 2>&1 | grep -v "schema" | grep -v "at"

    - name: Comment on PR
      if: github.event_name == 'pull_request' && inputs.comment_on_pr == 'yes'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        repo="${{ github.repository }}"

        comment_body="Database migrations were successfully deployed to the $NEXT_PUBLIC_CURRENT_ENV branch of the database."

        curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"${comment_body}\"}" \
          "https://api.github.com/repos/${repo}/issues/${pr_number}/comments"
